// app/layout.tsx

import type { Metadata } from "next";
// 💡 MODIFIED: Added Jost to the Google Fonts import
import { Geist, Geist_Mono, Inter, Bricolage_Grotesque, Jost } from "next/font/google";
import "../styles/globals.css";

// ❌ Removed: import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure Inter
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Define a CSS variable for Inter
  display: "swap",
});

// Configure Bricolage Grotesque
const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque", // Define a CSS variable for Bricolage Grotesque
  display: "swap",
});

// 💡 NEW: Configure Jost for your accent font
const jost = Jost({
  subsets: ["latin"],
  variable: "--font-accent-jost", // Use a descriptive variable name
  display: "swap",
});

// ❌ Removed the radnikaNext localFont block

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // 💡 MODIFIED: Replaced radnikaNext.variable with jost.variable
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${bricolageGrotesque.variable} ${jost.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}